
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwrufdjpoiwtjkgusmza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53cnVmZGpwb2l3dGprZ3VzbXphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NjM0NTEsImV4cCI6MjA2MDAzOTQ1MX0.btbVecy92sNS1CHd9fUUAQQhtTdV9stLch6_QspuuYc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
